export const SPECIALTIES_FR = [
  'Médecine générale',
  'Anesthésie-réanimation',
  'Cardiologie',
  'Chirurgie générale',
  'Chirurgie cardiaque',
  'Chirurgie digestive',
  'Chirurgie orthopédique et traumatologie',
  'Chirurgie plastique, reconstructrice et esthétique',
  'Chirurgie thoracique',
  'Chirurgie vasculaire',
  'Dermatologie',
  'Endocrinologie - Diabétologie - Nutrition',
  'Gastro-entérologie et hépatologie',
  'Gériatrie',
  'Gynécologie-obstétrique',
  'Hématologie',
  'Infectiologie',
  'Médecine d’urgence',
  'Médecine interne',
  'Médecine physique et de réadaptation',
  'Médecine du travail',
  'Néphrologie',
  'Neurologie',
  'Neurochirurgie',
  'Oncologie médicale',
  'ORL (Oto-rhino-laryngologie)',
  'Ophtalmologie',
  'Pédiatrie',
  'Pneumologie',
  'Psychiatrie',
  'Radiologie et imagerie médicale',
  'Rhumatologie',
  'Réanimation médicale',
  'Urologie',
  'Allergologie',
  'Andrologie',
  'Angiologie',
  'Stomatologie',
  'Odontologie',
  'Santé publique',
  'Médecine légale',
  'Médecine tropicale',
]

